#!/bin/sh
# Uruchamia lint-staged oraz testy jednostkowe na zmienionych plikach lub wszystkich
echo "🔍 Uruchamiam lint-staged..."
npx lint-staged

echo "🧪 Uruchamiam testy jednostkowe..."
npm run test:unit
